import logging
from config import client, DEFAULT_MODEL
from utils.markdown import (
    create_heading, create_subheading, create_blockquote,
    create_list, create_code_block
)

logger = logging.getLogger(__name__)


def generate_markdown(question: str, research_data: str) -> str:
    """Generate well-structured markdown study material"""
    if not client:
        logger.error("LLM client not initialized. Check API keys in .env")
        return ""
    
    if not question or not question.strip():
        logger.error("Question cannot be empty")
        return ""
    
    if not research_data or not research_data.strip():
        logger.warning("No research data provided")
        research_data = "No research data available"
    
    try:
        prompt = f"""Create comprehensive, well-structured study material in Markdown format.

Question: {question}

Guidelines:
- Use clear hierarchical headings (H1, H2, H3)
- Include an overview/introduction
- Break content into logical sections
- Add bullet points for key concepts
- Include important definitions in blockquotes
- Add code blocks where relevant with ```language``` markers
- Include mermaid diagrams where helpful using ```mermaid``` blocks
- Use proper markdown formatting
- Target language: student-friendly, clear explanations
- Include a "Key Points" summary section
- Include a "Further Reading" section with references
- Aim for 2000-3000 words

Research Data:
{research_data}

Generate only the markdown content, no preamble or explanations."""

        response = client.chat.completions.create(
            model=DEFAULT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=2500
        )
        
        markdown_content = response.choices[0].message.content.strip()
        
        # Add header and footer
        final_markdown = create_heading(question, 1)
        final_markdown += "\n"
        final_markdown += markdown_content
        final_markdown += "\n\n---\n"
        final_markdown += "*Generated by Study Material Maker*\n"
        
        logger.info(f"Generated markdown for question: {question}")
        return final_markdown
    
    except Exception as e:
        logger.error(f"Error generating markdown: {e}")
        return create_heading(f"Error: Unable to generate material for '{question}'", 1)


def generate_summary(content: str, max_points: int = 5) -> str:
    """Generate a summary of the content"""
    if not content or not content.strip():
        logger.warning("Content cannot be empty for summary")
        return ""
    
    try:
        prompt = f"""Summarize the following content into {max_points} key bullet points.
Keep each point concise (1 sentence max).
Return only the bullet points in markdown list format.

Content:
{content[:1000]}"""

        response = client.chat.completions.create(
            model=DEFAULT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=300
        )
        
        summary = response.choices[0].message.content.strip()
        logger.info("Generated summary")
        return summary
    
    except Exception as e:
        logger.error(f"Error generating summary: {e}")
        return ""


def generate_quiz_questions(content: str, num_questions: int = 5) -> list:
    """Generate quiz questions based on content"""
    if not content or not content.strip():
        logger.warning("Content cannot be empty for quiz generation")
        return []
    
    try:
        prompt = f"""Generate {num_questions} quiz questions based on the following content.
For each question, provide:
1. Question text
2. Four multiple-choice options (A, B, C, D)
3. Correct answer

Format as JSON array of objects.

Content:
{content[:1000]}"""

        response = client.chat.completions.create(
            model=DEFAULT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=1000
        )
        
        import json
        questions = json.loads(response.choices[0].message.content)
        logger.info(f"Generated {len(questions)} quiz questions")
        return questions
    
    except Exception as e:
        logger.error(f"Error generating quiz questions: {e}")
        return []
